// autogenerated

// swiftlint:disable all
import Foundation

public struct AlternativeDistributionPackageVariantsResponse: Hashable, Codable, Sendable {
    public var data: [AlternativeDistributionPackageVariant]

    public var links: PagedDocumentLinks

    public var meta: PagingInformation?

    public init(
        data: [AlternativeDistributionPackageVariant],
        links: PagedDocumentLinks,
        meta: PagingInformation? = nil
    ) {
        self.data = data
        self.links = links
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case links
        case meta
    }
}

// swiftlint:enable all
