// autogenerated

// swiftlint:disable all
import Foundation

public struct AndroidToIosAppMappingDetailResponse: Hashable, Codable, Sendable {
    public var data: AndroidToIosAppMappingDetail

    public var links: DocumentLinks

    public init(
        data: AndroidToIosAppMappingDetail,
        links: DocumentLinks
    ) {
        self.data = data
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case links
    }
}

// swiftlint:enable all
