// autogenerated

// swiftlint:disable all
import Foundation

public struct BetaFeedbackScreenshotSubmissionResponse: Hashable, Codable, Sendable {
    public var data: BetaFeedbackScreenshotSubmission

    public var included: [Included]?

    public var links: DocumentLinks

    public init(
        data: BetaFeedbackScreenshotSubmission,
        included: [Included]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }

    public enum Included: Hashable, Codable, Sendable {
        case betaTester(BetaTester)
        case build(Build)

        public init(from decoder: Decoder) throws {
            self = try {
                var lastError: Error!
                do {
                    return .betaTester(try BetaTester(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .build(try Build(from: decoder))
                } catch {
                    lastError = error
                }
                throw lastError
            }()
        }

        public func encode(to encoder: Encoder) throws {
            switch self {
            case .betaTester(let value):
                try value.encode(to: encoder)

            case .build(let value):
                try value.encode(to: encoder)
            }
        }
    }
}

// swiftlint:enable all
