// autogenerated

// swiftlint:disable all
import Foundation

public struct BetaBuildUsagesV1MetricResponse: Hashable, Codable, Sendable {
    public var data: [Data]

    public var links: PagedDocumentLinks

    public var meta: PagingInformation?

    public init(
        data: [Data],
        links: PagedDocumentLinks,
        meta: PagingInformation? = nil
    ) {
        self.data = data
        self.links = links
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case links
        case meta
    }

    public struct Data: Hashable, Codable, Sendable {
        public var dataPoints: DataPoints?

        public init(dataPoints: DataPoints? = nil) {
            self.dataPoints = dataPoints
        }

        private enum CodingKeys: String, CodingKey {
            case dataPoints
        }

        public struct DataPoints: Hashable, Codable, Sendable {
            public var end: String?

            public var start: String?

            public var values: Values?

            public init(
                end: String? = nil,
                start: String? = nil,
                values: Values? = nil
            ) {
                self.end = end
                self.start = start
                self.values = values
            }

            private enum CodingKeys: String, CodingKey {
                case end
                case start
                case values
            }

            public struct Values: Hashable, Codable, Sendable {
                public var crashCount: Int?

                public var feedbackCount: Int?

                public var installCount: Int?

                public var inviteCount: Int?

                public var sessionCount: Int?

                public init(
                    crashCount: Int? = nil,
                    feedbackCount: Int? = nil,
                    installCount: Int? = nil,
                    inviteCount: Int? = nil,
                    sessionCount: Int? = nil
                ) {
                    self.crashCount = crashCount
                    self.feedbackCount = feedbackCount
                    self.installCount = installCount
                    self.inviteCount = inviteCount
                    self.sessionCount = sessionCount
                }

                private enum CodingKeys: String, CodingKey {
                    case crashCount
                    case feedbackCount
                    case installCount
                    case inviteCount
                    case sessionCount
                }
            }
        }
    }
}

// swiftlint:enable all
