// autogenerated

// swiftlint:disable all
import Foundation

public struct GameCenterMatchmakingSessionsV1MetricResponse: Hashable, Codable, Sendable {
    public var data: [Data]

    public var links: PagedDocumentLinks

    public var meta: PagingInformation?

    public init(
        data: [Data],
        links: PagedDocumentLinks,
        meta: PagingInformation? = nil
    ) {
        self.data = data
        self.links = links
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case links
        case meta
    }

    public struct Data: Hashable, Codable, Sendable {
        public var dataPoints: DataPoints?

        public var granularity: Granularity?

        public init(
            dataPoints: DataPoints? = nil,
            granularity: Granularity? = nil
        ) {
            self.dataPoints = dataPoints
            self.granularity = granularity
        }

        private enum CodingKeys: String, CodingKey {
            case dataPoints
            case granularity
        }

        public struct DataPoints: Hashable, Codable, Sendable {
            public var end: String?

            public var start: String?

            public var values: Values?

            public init(
                end: String? = nil,
                start: String? = nil,
                values: Values? = nil
            ) {
                self.end = end
                self.start = start
                self.values = values
            }

            private enum CodingKeys: String, CodingKey {
                case end
                case start
                case values
            }

            public struct Values: Hashable, Codable, Sendable {
                public var averagePlayerCount: Float?

                public var count: Int?

                public var p50PlayerCount: Float?

                public var p95PlayerCount: Float?

                public init(
                    averagePlayerCount: Float? = nil,
                    count: Int? = nil,
                    p50PlayerCount: Float? = nil,
                    p95PlayerCount: Float? = nil
                ) {
                    self.averagePlayerCount = averagePlayerCount
                    self.count = count
                    self.p50PlayerCount = p50PlayerCount
                    self.p95PlayerCount = p95PlayerCount
                }

                private enum CodingKeys: String, CodingKey {
                    case averagePlayerCount
                    case count
                    case p50PlayerCount
                    case p95PlayerCount
                }
            }
        }

        public struct Granularity: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
            public static var p1D: Self {
                .init(rawValue: "P1D")
            }

            public static var pT15M: Self {
                .init(rawValue: "PT15M")
            }

            public static var pT1H: Self {
                .init(rawValue: "PT1H")
            }

            public var description: String {
                rawValue
            }

            public var rawValue: String

            public init(rawValue: String) {
                self.rawValue = rawValue
            }
        }
    }
}

// swiftlint:enable all
