// autogenerated

// swiftlint:disable all
import Foundation

public struct GameCenterChallengeVersionResponse: Hashable, Codable, Sendable {
    public var data: GameCenterChallengeVersion

    public var included: [Included]?

    public var links: DocumentLinks

    public init(
        data: GameCenterChallengeVersion,
        included: [Included]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }

    public enum Included: Hashable, Codable, Sendable {
        case gameCenterChallenge(GameCenterChallenge)
        case gameCenterChallengeLocalization(GameCenterChallengeLocalization)
        case gameCenterChallengeVersionRelease(GameCenterChallengeVersionRelease)
        case gameCenterChallengeImage(GameCenterChallengeImage)

        public init(from decoder: Decoder) throws {
            self = try {
                var lastError: Error!
                do {
                    return .gameCenterChallenge(try GameCenterChallenge(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterChallengeLocalization(try GameCenterChallengeLocalization(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterChallengeVersionRelease(try GameCenterChallengeVersionRelease(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterChallengeImage(try GameCenterChallengeImage(from: decoder))
                } catch {
                    lastError = error
                }
                throw lastError
            }()
        }

        public func encode(to encoder: Encoder) throws {
            switch self {
            case .gameCenterChallenge(let value):
                try value.encode(to: encoder)

            case .gameCenterChallengeLocalization(let value):
                try value.encode(to: encoder)

            case .gameCenterChallengeVersionRelease(let value):
                try value.encode(to: encoder)

            case .gameCenterChallengeImage(let value):
                try value.encode(to: encoder)
            }
        }
    }
}

// swiftlint:enable all
