// autogenerated

// swiftlint:disable all
import Foundation

public struct GameCenterChallengeResponse: Hashable, Codable, Sendable {
    public var data: GameCenterChallenge

    public var included: [Included]?

    public var links: DocumentLinks

    public init(
        data: GameCenterChallenge,
        included: [Included]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }

    public enum Included: Hashable, Codable, Sendable {
        case gameCenterChallengeVersion(GameCenterChallengeVersion)
        case gameCenterDetail(GameCenterDetail)
        case gameCenterGroup(GameCenterGroup)
        case gameCenterLeaderboard(GameCenterLeaderboard)

        public init(from decoder: Decoder) throws {
            self = try {
                var lastError: Error!
                do {
                    return .gameCenterChallengeVersion(try GameCenterChallengeVersion(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterDetail(try GameCenterDetail(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterGroup(try GameCenterGroup(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterLeaderboard(try GameCenterLeaderboard(from: decoder))
                } catch {
                    lastError = error
                }
                throw lastError
            }()
        }

        public func encode(to encoder: Encoder) throws {
            switch self {
            case .gameCenterChallengeVersion(let value):
                try value.encode(to: encoder)

            case .gameCenterDetail(let value):
                try value.encode(to: encoder)

            case .gameCenterGroup(let value):
                try value.encode(to: encoder)

            case .gameCenterLeaderboard(let value):
                try value.encode(to: encoder)
            }
        }
    }
}

// swiftlint:enable all
