// autogenerated

// swiftlint:disable all
import Foundation

public struct GameCenterChallengeLocalizationsResponse: Hashable, Codable, Sendable {
    public var data: [GameCenterChallengeLocalization]

    public var included: [Included]?

    public var links: PagedDocumentLinks

    public var meta: PagingInformation?

    public init(
        data: [GameCenterChallengeLocalization],
        included: [Included]? = nil,
        links: PagedDocumentLinks,
        meta: PagingInformation? = nil
    ) {
        self.data = data
        self.included = included
        self.links = links
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
        case meta
    }

    public enum Included: Hashable, Codable, Sendable {
        case gameCenterChallengeImage(GameCenterChallengeImage)
        case gameCenterChallengeVersion(GameCenterChallengeVersion)

        public init(from decoder: Decoder) throws {
            self = try {
                var lastError: Error!
                do {
                    return .gameCenterChallengeImage(try GameCenterChallengeImage(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .gameCenterChallengeVersion(try GameCenterChallengeVersion(from: decoder))
                } catch {
                    lastError = error
                }
                throw lastError
            }()
        }

        public func encode(to encoder: Encoder) throws {
            switch self {
            case .gameCenterChallengeImage(let value):
                try value.encode(to: encoder)

            case .gameCenterChallengeVersion(let value):
                try value.encode(to: encoder)
            }
        }
    }
}

// swiftlint:enable all
