// autogenerated

// swiftlint:disable all
import Foundation

public struct InAppPurchaseSubmissionResponse: Hashable, Codable, Sendable {
    public var data: InAppPurchaseSubmission

    public var included: [InAppPurchaseV2]?

    public var links: DocumentLinks

    public init(
        data: InAppPurchaseSubmission,
        included: [InAppPurchaseV2]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }
}

// swiftlint:enable all
