// autogenerated

// swiftlint:disable all
import Foundation

public struct SubscriptionAvailabilityResponse: Hashable, Codable {
    public var data: SubscriptionAvailability

    public var included: [Included]?

    public var links: DocumentLinks

    public init(
        data: SubscriptionAvailability,
        included: [Included]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }

    public enum Included: Hashable, Codable {
        case subscription(Subscription)
        case territory(Territory)

        public init(from decoder: Decoder) throws {
            self = try {
                var lastError: Error!
                do {
                    return .subscription(try Subscription(from: decoder))
                } catch {
                    lastError = error
                }
                do {
                    return .territory(try Territory(from: decoder))
                } catch {
                    lastError = error
                }
                throw lastError
            }()
        }

        public func encode(to encoder: Encoder) throws {
            switch self {
            case .subscription(let value):
                try value.encode(to: encoder)

            case .territory(let value):
                try value.encode(to: encoder)
            }
        }
    }
}

// swiftlint:enable all
