// autogenerated

// swiftlint:disable all
import Foundation

public struct SubscriptionGroupLocalizationResponse: Hashable, Codable, Sendable {
    public var data: SubscriptionGroupLocalization

    public var included: [SubscriptionGroup]?

    public var links: DocumentLinks

    public init(
        data: SubscriptionGroupLocalization,
        included: [SubscriptionGroup]? = nil,
        links: DocumentLinks
    ) {
        self.data = data
        self.included = included
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case included
        case links
    }
}

// swiftlint:enable all
