// autogenerated

// swiftlint:disable all
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension V1.InAppPurchaseOfferCodes.ById.CustomCodes {
    public struct GET: Endpoint {
        public typealias Response = InAppPurchaseOfferCodeCustomCodesResponse

        public var path: String {
            "/v1/inAppPurchaseOfferCodes/\(id)/customCodes"
        }

        /// the id of the requested resource
        public var id: String

        public var parameters: Parameters = Parameters()

        public init(id: String) {
            self.id = id
        }

        public func request(with baseURL: URL) throws -> URLRequest? {
            var components = URLComponents(url: baseURL, resolvingAgainstBaseURL: true)
            components?.path = path

            components?.queryItems = [
                URLQueryItem(name: "fields[actors]",
                             value: parameters.fields[.actors]?.map { "\($0)" }.joined(separator: ",")),
                URLQueryItem(name: "fields[inAppPurchaseOfferCodeCustomCodes]",
                             value: parameters.fields[.inAppPurchaseOfferCodeCustomCodes]?.map { "\($0)" }.joined(separator: ",")),
                URLQueryItem(name: "include",
                             value: parameters.include?.map { "\($0)" }.joined(separator: ",")),
                URLQueryItem(name: "limit",
                             value: parameters.limit.map { "\($0)" })
            ].filter { $0.value != nil }
            if components?.queryItems?.isEmpty ?? false {
                components?.queryItems = nil
            }

            var urlRequest = components?.url.map { URLRequest(url: $0) }
            urlRequest?.httpMethod = "GET"
            return urlRequest
        }

        /// - Returns: **200**, List of InAppPurchaseOfferCodeCustomCodes as `InAppPurchaseOfferCodeCustomCodesResponse`
        /// - Throws: **400**, Parameter error(s) as `ErrorResponse`
        /// - Throws: **401**, Unauthorized error(s) as `ErrorResponse`
        /// - Throws: **403**, Forbidden error as `ErrorResponse`
        /// - Throws: **404**, Not found error as `ErrorResponse`
        /// - Throws: **429**, Rate limit exceeded error as `ErrorResponse`
        public static func response(from data: Data, urlResponse: HTTPURLResponse) throws -> Response {
            var jsonDecoder: JSONDecoder {
                let decoder = JSONDecoder()
                return decoder
            }

            switch urlResponse.statusCode {
            case 200:
                return try jsonDecoder.decode(InAppPurchaseOfferCodeCustomCodesResponse.self, from: data)

            case 400:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)

            case 401:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)

            case 403:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)

            case 404:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)

            case 429:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)

            default:
                throw try jsonDecoder.decode(ErrorResponse.self, from: data)
            }
        }
    }
}

extension V1.InAppPurchaseOfferCodes.ById.CustomCodes.GET {
    public struct Parameters: Hashable {
        public var fields: Fields = Fields()

        /// comma-separated list of relationships to include
        public var include: [Include]?

        /// maximum resources per page
        public var limit: Int?

        public struct Fields: Hashable {
            public subscript <T: Hashable>(_ relation: Relation<T>) -> T {
                get { values[relation]?.base as! T }
                set { values[relation] = AnyHashable(newValue) }
            }

            private var values: [AnyHashable: AnyHashable] = [:]

            public struct Actors: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
                public static var actorType: Self {
                    .init(rawValue: "actorType")
                }

                public static var apiKeyId: Self {
                    .init(rawValue: "apiKeyId")
                }

                public static var userEmail: Self {
                    .init(rawValue: "userEmail")
                }

                public static var userFirstName: Self {
                    .init(rawValue: "userFirstName")
                }

                public static var userLastName: Self {
                    .init(rawValue: "userLastName")
                }

                public var description: String {
                    rawValue
                }

                public var rawValue: String

                public init(rawValue: String) {
                    self.rawValue = rawValue
                }
            }

            public struct InAppPurchaseOfferCodeCustomCodes: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
                public static var active: Self {
                    .init(rawValue: "active")
                }

                public static var createdByActor: Self {
                    .init(rawValue: "createdByActor")
                }

                public static var createdDate: Self {
                    .init(rawValue: "createdDate")
                }

                public static var customCode: Self {
                    .init(rawValue: "customCode")
                }

                public static var deactivatedByActor: Self {
                    .init(rawValue: "deactivatedByActor")
                }

                public static var expirationDate: Self {
                    .init(rawValue: "expirationDate")
                }

                public static var numberOfCodes: Self {
                    .init(rawValue: "numberOfCodes")
                }

                public var description: String {
                    rawValue
                }

                public var rawValue: String

                public init(rawValue: String) {
                    self.rawValue = rawValue
                }
            }

            public struct Relation<T>: Hashable {
                /// the fields to include for returned resources of type actors
                public static var actors: Relation<[Actors]?> {
                    .init(key: "fields[actors]")
                }

                /// the fields to include for returned resources of type inAppPurchaseOfferCodeCustomCodes
                public static var inAppPurchaseOfferCodeCustomCodes: Relation<[InAppPurchaseOfferCodeCustomCodes]?> {
                    .init(key: "fields[inAppPurchaseOfferCodeCustomCodes]")
                }

                internal let key: String

                public func hash(into hasher: inout Hasher) {
                    hasher.combine(key)
                }
            }
        }

        public struct Include: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
            public static var createdByActor: Self {
                .init(rawValue: "createdByActor")
            }

            public static var deactivatedByActor: Self {
                .init(rawValue: "deactivatedByActor")
            }

            public var description: String {
                rawValue
            }

            public var rawValue: String

            public init(rawValue: String) {
                self.rawValue = rawValue
            }
        }
    }
}

// swiftlint:enable all
