// autogenerated

// swiftlint:disable all
import Foundation

public struct AppEncryptionDeclarationCreateRequest: Hashable, Codable, Sendable {
    public var data: Data

    public init(data: Data) {
        self.data = data
    }

    private enum CodingKeys: String, CodingKey {
        case data
    }

    public struct Data: Hashable, Codable, Sendable {
        public var type: `Type`

        public var attributes: Attributes

        public var relationships: Relationships

        public init(
            type: `Type`,
            attributes: Attributes,
            relationships: Relationships
        ) {
            self.type = type
            self.attributes = attributes
            self.relationships = relationships
        }

        private enum CodingKeys: String, CodingKey {
            case type
            case attributes
            case relationships
        }

        public enum `Type`: String, Hashable, Codable, Sendable {
            case appEncryptionDeclarations
        }

        public struct Attributes: Hashable, Codable, Sendable {
            public var appDescription: String

            public var availableOnFrenchStore: Bool

            public var containsProprietaryCryptography: Bool

            public var containsThirdPartyCryptography: Bool

            public init(
                appDescription: String,
                availableOnFrenchStore: Bool,
                containsProprietaryCryptography: Bool,
                containsThirdPartyCryptography: Bool
            ) {
                self.appDescription = appDescription
                self.availableOnFrenchStore = availableOnFrenchStore
                self.containsProprietaryCryptography = containsProprietaryCryptography
                self.containsThirdPartyCryptography = containsThirdPartyCryptography
            }

            private enum CodingKeys: String, CodingKey {
                case appDescription
                case availableOnFrenchStore
                case containsProprietaryCryptography
                case containsThirdPartyCryptography
            }
        }

        public struct Relationships: Hashable, Codable, Sendable {
            @available(*, deprecated)
            public var app: App

            public init(app: App) {
                self.app = app
            }

            private enum CodingKeys: String, CodingKey {
                case app
            }

            public struct App: Hashable, Codable, Sendable {
                public var data: Data

                public init(data: Data) {
                    self.data = data
                }

                private enum CodingKeys: String, CodingKey {
                    case data
                }

                public struct Data: Hashable, Codable, Sendable {
                    public var id: String

                    public var type: `Type`

                    public init(
                        id: String,
                        type: `Type`
                    ) {
                        self.id = id
                        self.type = type
                    }

                    private enum CodingKeys: String, CodingKey {
                        case id
                        case type
                    }

                    public enum `Type`: String, Hashable, Codable, Sendable {
                        case apps
                    }
                }
            }
        }
    }
}

// swiftlint:enable all
