// autogenerated

// swiftlint:disable all
import Foundation

public struct DeviceCreateRequest: Hashable, Codable {
    public var data: Data

    public init(data: Data) {
        self.data = data
    }

    private enum CodingKeys: String, CodingKey {
        case data
    }

    public struct Data: Hashable, Codable {
        public var type: `Type`

        public var attributes: Attributes

        public init(
            type: `Type`,
            attributes: Attributes
        ) {
            self.type = type
            self.attributes = attributes
        }

        private enum CodingKeys: String, CodingKey {
            case type
            case attributes
        }

        public enum `Type`: String, Hashable, Codable {
            case devices
        }

        public struct Attributes: Hashable, Codable {
            public var name: String

            public var platform: BundleIdPlatform

            public var udid: String

            public init(
                name: String,
                platform: BundleIdPlatform,
                udid: String
            ) {
                self.name = name
                self.platform = platform
                self.udid = udid
            }

            private enum CodingKeys: String, CodingKey {
                case name
                case platform
                case udid
            }
        }
    }
}

// swiftlint:enable all
