// autogenerated

// swiftlint:disable all
import Foundation

public struct GameCenterActivityImageCreateRequest: Hashable, Codable, Sendable {
    public var data: Data

    public init(data: Data) {
        self.data = data
    }

    private enum CodingKeys: String, CodingKey {
        case data
    }

    public struct Data: Hashable, Codable, Sendable {
        public var type: `Type`

        public var attributes: Attributes

        public var relationships: Relationships?

        public init(
            type: `Type`,
            attributes: Attributes,
            relationships: Relationships? = nil
        ) {
            self.type = type
            self.attributes = attributes
            self.relationships = relationships
        }

        private enum CodingKeys: String, CodingKey {
            case type
            case attributes
            case relationships
        }

        public enum `Type`: String, Hashable, Codable, Sendable {
            case gameCenterActivityImages
        }

        public struct Attributes: Hashable, Codable, Sendable {
            public var fileName: String

            public var fileSize: Int

            public init(
                fileName: String,
                fileSize: Int
            ) {
                self.fileName = fileName
                self.fileSize = fileSize
            }

            private enum CodingKeys: String, CodingKey {
                case fileName
                case fileSize
            }
        }

        public struct Relationships: Hashable, Codable, Sendable {
            public var localization: Localization?

            public var version: Version?

            public init(
                localization: Localization? = nil,
                version: Version? = nil
            ) {
                self.localization = localization
                self.version = version
            }

            private enum CodingKeys: String, CodingKey {
                case localization
                case version
            }

            public struct Localization: Hashable, Codable, Sendable {
                public var data: Data?

                public init(data: Data? = nil) {
                    self.data = data
                }

                private enum CodingKeys: String, CodingKey {
                    case data
                }

                public struct Data: Hashable, Codable, Sendable {
                    public var id: String

                    public var type: `Type`

                    public init(
                        id: String,
                        type: `Type`
                    ) {
                        self.id = id
                        self.type = type
                    }

                    private enum CodingKeys: String, CodingKey {
                        case id
                        case type
                    }

                    public enum `Type`: String, Hashable, Codable, Sendable {
                        case gameCenterActivityLocalizations
                    }
                }
            }

            public struct Version: Hashable, Codable, Sendable {
                public var data: Data?

                public init(data: Data? = nil) {
                    self.data = data
                }

                private enum CodingKeys: String, CodingKey {
                    case data
                }

                public struct Data: Hashable, Codable, Sendable {
                    public var id: String

                    public var type: `Type`

                    public init(
                        id: String,
                        type: `Type`
                    ) {
                        self.id = id
                        self.type = type
                    }

                    private enum CodingKeys: String, CodingKey {
                        case id
                        case type
                    }

                    public enum `Type`: String, Hashable, Codable, Sendable {
                        case gameCenterActivityVersions
                    }
                }
            }
        }
    }
}

// swiftlint:enable all
