// autogenerated

// swiftlint:disable all
import Foundation

public struct AccessibilityDeclaration: Hashable, Codable, Sendable {
    public var id: String

    public var type: `Type`

    public var attributes: Attributes?

    public var links: ResourceLinks?

    public init(
        id: String,
        type: `Type`,
        attributes: Attributes? = nil,
        links: ResourceLinks? = nil
    ) {
        self.id = id
        self.type = type
        self.attributes = attributes
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case attributes
        case links
    }

    public enum `Type`: String, Hashable, Codable, Sendable {
        case accessibilityDeclarations
    }

    public struct Attributes: Hashable, Codable, Sendable {
        public var deviceFamily: DeviceFamily?

        public var state: State?

        public var supportsAudioDescriptions: Bool?

        public var supportsCaptions: Bool?

        public var supportsDarkInterface: Bool?

        public var supportsDifferentiateWithoutColorAlone: Bool?

        public var supportsLargerText: Bool?

        public var supportsReducedMotion: Bool?

        public var supportsSufficientContrast: Bool?

        public var supportsVoiceControl: Bool?

        public var supportsVoiceover: Bool?

        public init(
            deviceFamily: DeviceFamily? = nil,
            state: State? = nil,
            supportsAudioDescriptions: Bool? = nil,
            supportsCaptions: Bool? = nil,
            supportsDarkInterface: Bool? = nil,
            supportsDifferentiateWithoutColorAlone: Bool? = nil,
            supportsLargerText: Bool? = nil,
            supportsReducedMotion: Bool? = nil,
            supportsSufficientContrast: Bool? = nil,
            supportsVoiceControl: Bool? = nil,
            supportsVoiceover: Bool? = nil
        ) {
            self.deviceFamily = deviceFamily
            self.state = state
            self.supportsAudioDescriptions = supportsAudioDescriptions
            self.supportsCaptions = supportsCaptions
            self.supportsDarkInterface = supportsDarkInterface
            self.supportsDifferentiateWithoutColorAlone = supportsDifferentiateWithoutColorAlone
            self.supportsLargerText = supportsLargerText
            self.supportsReducedMotion = supportsReducedMotion
            self.supportsSufficientContrast = supportsSufficientContrast
            self.supportsVoiceControl = supportsVoiceControl
            self.supportsVoiceover = supportsVoiceover
        }

        private enum CodingKeys: String, CodingKey {
            case deviceFamily
            case state
            case supportsAudioDescriptions
            case supportsCaptions
            case supportsDarkInterface
            case supportsDifferentiateWithoutColorAlone
            case supportsLargerText
            case supportsReducedMotion
            case supportsSufficientContrast
            case supportsVoiceControl
            case supportsVoiceover
        }

        public struct State: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
            public static var draft: Self {
                .init(rawValue: "DRAFT")
            }

            public static var published: Self {
                .init(rawValue: "PUBLISHED")
            }

            public static var replaced: Self {
                .init(rawValue: "REPLACED")
            }

            public var description: String {
                rawValue
            }

            public var rawValue: String

            public init(rawValue: String) {
                self.rawValue = rawValue
            }
        }
    }
}

// swiftlint:enable all
