// autogenerated

// swiftlint:disable all
import Foundation

public struct AlternativeDistributionPackage: Hashable, Codable, Sendable {
    public var id: String

    public var type: `Type`

    public var relationships: Relationships?

    public var links: ResourceLinks?

    public init(
        id: String,
        type: `Type`,
        relationships: Relationships? = nil,
        links: ResourceLinks? = nil
    ) {
        self.id = id
        self.type = type
        self.relationships = relationships
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case relationships
        case links
    }

    public enum `Type`: String, Hashable, Codable, Sendable {
        case alternativeDistributionPackages
    }

    public struct Relationships: Hashable, Codable, Sendable {
        public var versions: Versions?

        public init(versions: Versions? = nil) {
            self.versions = versions
        }

        private enum CodingKeys: String, CodingKey {
            case versions
        }

        public struct Versions: Hashable, Codable, Sendable {
            public var data: [Data]?

            public var links: RelationshipLinks?

            public var meta: PagingInformation?

            public init(
                data: [Data]? = nil,
                links: RelationshipLinks? = nil,
                meta: PagingInformation? = nil
            ) {
                self.data = data
                self.links = links
                self.meta = meta
            }

            private enum CodingKeys: String, CodingKey {
                case data
                case links
                case meta
            }

            public struct Data: Hashable, Codable, Sendable {
                public var id: String

                public var type: `Type`

                public init(
                    id: String,
                    type: `Type`
                ) {
                    self.id = id
                    self.type = type
                }

                private enum CodingKeys: String, CodingKey {
                    case id
                    case type
                }

                public enum `Type`: String, Hashable, Codable, Sendable {
                    case alternativeDistributionPackageVersions
                }
            }
        }
    }
}

// swiftlint:enable all
