// autogenerated

// swiftlint:disable all
import Foundation

public struct CiBranchStartCondition: Hashable, Codable, Sendable {
    public var autoCancel: Bool?

    public var filesAndFoldersRule: CiFilesAndFoldersRule?

    public var source: CiBranchPatterns?

    public init(
        autoCancel: Bool? = nil,
        filesAndFoldersRule: CiFilesAndFoldersRule? = nil,
        source: CiBranchPatterns? = nil
    ) {
        self.autoCancel = autoCancel
        self.filesAndFoldersRule = filesAndFoldersRule
        self.source = source
    }

    private enum CodingKeys: String, CodingKey {
        case autoCancel
        case filesAndFoldersRule
        case source
    }
}

// swiftlint:enable all
