// autogenerated

// swiftlint:disable all
import Foundation

public struct FileLocation: Hashable, Codable, Sendable {
    public var lineNumber: Int?

    public var path: String?

    public init(
        lineNumber: Int? = nil,
        path: String? = nil
    ) {
        self.lineNumber = lineNumber
        self.path = path
    }

    private enum CodingKeys: String, CodingKey {
        case lineNumber
        case path
    }
}

// swiftlint:enable all
