// autogenerated

// swiftlint:disable all
import Foundation

public struct InAppPurchaseState: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
    public static var approved: Self {
        .init(rawValue: "APPROVED")
    }

    public static var developerActionNeeded: Self {
        .init(rawValue: "DEVELOPER_ACTION_NEEDED")
    }

    public static var developerRemovedFromSale: Self {
        .init(rawValue: "DEVELOPER_REMOVED_FROM_SALE")
    }

    public static var inReview: Self {
        .init(rawValue: "IN_REVIEW")
    }

    public static var missingMetadata: Self {
        .init(rawValue: "MISSING_METADATA")
    }

    public static var pendingBinaryApproval: Self {
        .init(rawValue: "PENDING_BINARY_APPROVAL")
    }

    public static var processingContent: Self {
        .init(rawValue: "PROCESSING_CONTENT")
    }

    public static var readyToSubmit: Self {
        .init(rawValue: "READY_TO_SUBMIT")
    }

    public static var rejected: Self {
        .init(rawValue: "REJECTED")
    }

    public static var removedFromSale: Self {
        .init(rawValue: "REMOVED_FROM_SALE")
    }

    public static var waitingForReview: Self {
        .init(rawValue: "WAITING_FOR_REVIEW")
    }

    public static var waitingForUpload: Self {
        .init(rawValue: "WAITING_FOR_UPLOAD")
    }

    public var description: String {
        rawValue
    }

    public var rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }
}

// swiftlint:enable all
