// autogenerated

// swiftlint:disable all
import Foundation

public enum PreviewType: String, Hashable, Codable {
    case appleTv = "APPLE_TV"
    case desktop = "DESKTOP"
    case ipad105 = "IPAD_105"
    case ipad97 = "IPAD_97"
    case ipadPro129 = "IPAD_PRO_129"
    case ipadPro3Gen11 = "IPAD_PRO_3GEN_11"
    case ipadPro3Gen129 = "IPAD_PRO_3GEN_129"
    case iphone35 = "IPHONE_35"
    case iphone40 = "IPHONE_40"
    case iphone47 = "IPHONE_47"
    case iphone55 = "IPHONE_55"
    case iphone58 = "IPHONE_58"
    case iphone65 = "IPHONE_65"
    case watchSeries3 = "WATCH_SERIES_3"
    case watchSeries4 = "WATCH_SERIES_4"
}

// swiftlint:enable all
