// autogenerated

// swiftlint:disable all
import Foundation

public struct SubscriptionVersion: Hashable, Codable, Sendable {
    public var id: String

    public var type: `Type`

    public var attributes: Attributes?

    public var relationships: Relationships?

    public var links: ResourceLinks?

    public init(
        id: String,
        type: `Type`,
        attributes: Attributes? = nil,
        relationships: Relationships? = nil,
        links: ResourceLinks? = nil
    ) {
        self.id = id
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case attributes
        case relationships
        case links
    }

    public enum `Type`: String, Hashable, Codable, Sendable {
        case subscriptionVersions
    }

    public struct Attributes: Hashable, Codable, Sendable {
        public var state: State?

        public var version: Int?

        public init(
            state: State? = nil,
            version: Int? = nil
        ) {
            self.state = state
            self.version = version
        }

        private enum CodingKeys: String, CodingKey {
            case state
            case version
        }

        public struct State: Hashable, Codable, RawRepresentable, CustomStringConvertible, Sendable {
            public static var accepted: Self {
                .init(rawValue: "ACCEPTED")
            }

            public static var approved: Self {
                .init(rawValue: "APPROVED")
            }

            public static var developerRejected: Self {
                .init(rawValue: "DEVELOPER_REJECTED")
            }

            public static var inReview: Self {
                .init(rawValue: "IN_REVIEW")
            }

            public static var prepareForSubmission: Self {
                .init(rawValue: "PREPARE_FOR_SUBMISSION")
            }

            public static var readyForReview: Self {
                .init(rawValue: "READY_FOR_REVIEW")
            }

            public static var rejected: Self {
                .init(rawValue: "REJECTED")
            }

            public static var replacedWithNewVersion: Self {
                .init(rawValue: "REPLACED_WITH_NEW_VERSION")
            }

            public static var waitingForReview: Self {
                .init(rawValue: "WAITING_FOR_REVIEW")
            }

            public var description: String {
                rawValue
            }

            public var rawValue: String

            public init(rawValue: String) {
                self.rawValue = rawValue
            }
        }
    }

    public struct Relationships: Hashable, Codable, Sendable {
        public var image: Image?

        public var images: Images?

        public var localizations: Localizations?

        public var subscription: Subscription?

        public init(
            image: Image? = nil,
            images: Images? = nil,
            localizations: Localizations? = nil,
            subscription: Subscription? = nil
        ) {
            self.image = image
            self.images = images
            self.localizations = localizations
            self.subscription = subscription
        }

        private enum CodingKeys: String, CodingKey {
            case image
            case images
            case localizations
            case subscription
        }

        public struct Image: Hashable, Codable, Sendable {
            public var data: Data?

            public var links: RelationshipLinks?

            public init(
                data: Data? = nil,
                links: RelationshipLinks? = nil
            ) {
                self.data = data
                self.links = links
            }

            private enum CodingKeys: String, CodingKey {
                case data
                case links
            }

            public struct Data: Hashable, Codable, Sendable {
                public var id: String

                public var type: `Type`

                public init(
                    id: String,
                    type: `Type`
                ) {
                    self.id = id
                    self.type = type
                }

                private enum CodingKeys: String, CodingKey {
                    case id
                    case type
                }

                public enum `Type`: String, Hashable, Codable, Sendable {
                    case subscriptionImages
                }
            }
        }

        public struct Images: Hashable, Codable, Sendable {
            public var data: [Data]?

            public var links: RelationshipLinks?

            public var meta: PagingInformation?

            public init(
                data: [Data]? = nil,
                links: RelationshipLinks? = nil,
                meta: PagingInformation? = nil
            ) {
                self.data = data
                self.links = links
                self.meta = meta
            }

            private enum CodingKeys: String, CodingKey {
                case data
                case links
                case meta
            }

            public struct Data: Hashable, Codable, Sendable {
                public var id: String

                public var type: `Type`

                public init(
                    id: String,
                    type: `Type`
                ) {
                    self.id = id
                    self.type = type
                }

                private enum CodingKeys: String, CodingKey {
                    case id
                    case type
                }

                public enum `Type`: String, Hashable, Codable, Sendable {
                    case subscriptionImages
                }
            }
        }

        public struct Localizations: Hashable, Codable, Sendable {
            public var data: [Data]?

            public var links: RelationshipLinks?

            public var meta: PagingInformation?

            public init(
                data: [Data]? = nil,
                links: RelationshipLinks? = nil,
                meta: PagingInformation? = nil
            ) {
                self.data = data
                self.links = links
                self.meta = meta
            }

            private enum CodingKeys: String, CodingKey {
                case data
                case links
                case meta
            }

            public struct Data: Hashable, Codable, Sendable {
                public var id: String

                public var type: `Type`

                public init(
                    id: String,
                    type: `Type`
                ) {
                    self.id = id
                    self.type = type
                }

                private enum CodingKeys: String, CodingKey {
                    case id
                    case type
                }

                public enum `Type`: String, Hashable, Codable, Sendable {
                    case subscriptionLocalizations
                }
            }
        }

        public struct Subscription: Hashable, Codable, Sendable {
            public var data: Data?

            public init(data: Data? = nil) {
                self.data = data
            }

            private enum CodingKeys: String, CodingKey {
                case data
            }

            public struct Data: Hashable, Codable, Sendable {
                public var id: String

                public var type: `Type`

                public init(
                    id: String,
                    type: `Type`
                ) {
                    self.id = id
                    self.type = type
                }

                private enum CodingKeys: String, CodingKey {
                    case id
                    case type
                }

                public enum `Type`: String, Hashable, Codable, Sendable {
                    case subscriptions
                }
            }
        }
    }
}

// swiftlint:enable all
